[project]
name = "calculatorlibrary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flake8>=7.3.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]
