# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies con uv
          command: |
            uv sync --all-extras --dev
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            uv run flake8 --exclude=.venv* --statistics
            uv run pytest -v --cov=calculator